name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile --output ./publish 

    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
         name: NumberDrawing
         path: ./publish/NumberDrawing.exe

  release:
    runs-on: windows-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./releases

      - name: Upload to releases
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./releases
